# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'
inhibit_all_warnings!

target 'CoinCapDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CoinCapDemo
  pod 'RxSwift'
  pod 'RxCocoa'
  pod "Resolver"
  pod 'SnapKit'

end
